export interface DocumentTemplate {
  id: string
  name: string
  description: string
  category: 'allgemein' | 'geschaeftlich' | 'akademisch' | 'persoenlich'
  content: unknown // Tiptap JSON
}

export const DEFAULT_TEMPLATES: DocumentTemplate[] = [
  {
    id: 'blank',
    name: 'Leeres Dokument',
    description: 'Ein leeres Dokument ohne Inhalt.',
    category: 'allgemein',
    content: {
      type: 'doc',
      content: [{ type: 'paragraph' }],
    },
  },
  {
    id: 'brief',
    name: 'Brief',
    description: 'Standard-Briefvorlage mit Absender, Empfaenger und Betreff.',
    category: 'geschaeftlich',
    content: {
      type: 'doc',
      content: [
        { type: 'paragraph', attrs: { textAlign: 'right' }, content: [{ type: 'text', text: 'Max Mustermann' }] },
        { type: 'paragraph', attrs: { textAlign: 'right' }, content: [{ type: 'text', text: 'Musterstrasse 1' }] },
        { type: 'paragraph', attrs: { textAlign: 'right' }, content: [{ type: 'text', text: '8000 Zuerich' }] },
        { type: 'paragraph' },
        { type: 'paragraph', content: [{ type: 'text', text: 'Firma / Person' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Strasse Nr.' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'PLZ Ort' }] },
        { type: 'paragraph' },
        { type: 'paragraph', attrs: { textAlign: 'right' }, content: [{ type: 'text', text: 'Zuerich, ' + new Date().toLocaleDateString('de-CH') }] },
        { type: 'paragraph' },
        { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Betreff: Ihr Betreff' }] },
        { type: 'paragraph' },
        { type: 'paragraph', content: [{ type: 'text', text: 'Sehr geehrte Damen und Herren,' }] },
        { type: 'paragraph' },
        { type: 'paragraph', content: [{ type: 'text', text: 'Ihr Text hier...' }] },
        { type: 'paragraph' },
        { type: 'paragraph', content: [{ type: 'text', text: 'Mit freundlichen Gruessen' }] },
        { type: 'paragraph' },
        { type: 'paragraph', content: [{ type: 'text', text: 'Max Mustermann' }] },
      ],
    },
  },
  {
    id: 'bericht',
    name: 'Bericht',
    description: 'Strukturierte Berichtsvorlage mit Titel und Abschnitten.',
    category: 'geschaeftlich',
    content: {
      type: 'doc',
      content: [
        { type: 'heading', attrs: { level: 1 }, content: [{ type: 'text', text: 'Berichtstitel' }] },
        { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'italic' }], text: 'Autor: Name | Datum: ' + new Date().toLocaleDateString('de-CH') }] },
        { type: 'horizontalRule' },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '1. Zusammenfassung' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Zusammenfassung des Berichts...' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '2. Einleitung' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Hintergrund und Zielsetzung...' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '3. Hauptteil' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Detaillierte Ausführungen...' }] },
        { type: 'heading', attrs: { level: 3 }, content: [{ type: 'text', text: '3.1 Unterabschnitt' }] },
        { type: 'paragraph', content: [{ type: 'text', text: '...' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '4. Fazit' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Schlussfolgerungen und Empfehlungen...' }] },
      ],
    },
  },
  {
    id: 'lebenslauf',
    name: 'Lebenslauf',
    description: 'Professioneller Lebenslauf mit Abschnitten.',
    category: 'persoenlich',
    content: {
      type: 'doc',
      content: [
        { type: 'heading', attrs: { level: 1 }, content: [{ type: 'text', text: 'Max Mustermann' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Musterstrasse 1 | 8000 Zuerich | max@example.com | +41 79 123 45 67' }] },
        { type: 'horizontalRule' },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Berufserfahrung' }] },
        { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Position' }, { type: 'text', text: ' — Firma, Ort (2020–heute)' }] },
        { type: 'bulletList', content: [{ type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Aufgabenbeschreibung' }] }] }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Ausbildung' }] },
        { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Abschluss' }, { type: 'text', text: ' — Institution (2016–2020)' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Kenntnisse' }] },
        { type: 'bulletList', content: [
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Sprachen: Deutsch (Muttersprache), Englisch (Fliessend)' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'IT: Microsoft Office, ...' }] }] },
        ] },
      ],
    },
  },
  {
    id: 'seminararbeit',
    name: 'Seminararbeit',
    description: 'Akademische Vorlage mit Titelblatt, Inhaltsverzeichnis und Struktur.',
    category: 'akademisch',
    content: {
      type: 'doc',
      content: [
        { type: 'paragraph' },
        { type: 'paragraph' },
        { type: 'heading', attrs: { level: 1, textAlign: 'center' }, content: [{ type: 'text', text: 'Titel der Seminararbeit' }] },
        { type: 'paragraph', attrs: { textAlign: 'center' }, content: [{ type: 'text', text: 'Vorgelegt von: Name' }] },
        { type: 'paragraph', attrs: { textAlign: 'center' }, content: [{ type: 'text', text: 'Betreuer: Prof. Dr. Name' }] },
        { type: 'paragraph', attrs: { textAlign: 'center' }, content: [{ type: 'text', text: 'Universitaet Zuerich | ' + new Date().toLocaleDateString('de-CH', { month: 'long', year: 'numeric' }) }] },
        { type: 'paragraph' },
        { type: 'paragraph' },
        { type: 'horizontalRule' },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '1. Einleitung' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Problemstellung und Zielsetzung...' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '2. Theoretischer Rahmen' }] },
        { type: 'paragraph', content: [{ type: 'text', text: '...' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '3. Methodik' }] },
        { type: 'paragraph', content: [{ type: 'text', text: '...' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '4. Ergebnisse' }] },
        { type: 'paragraph', content: [{ type: 'text', text: '...' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '5. Diskussion' }] },
        { type: 'paragraph', content: [{ type: 'text', text: '...' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '6. Fazit' }] },
        { type: 'paragraph', content: [{ type: 'text', text: '...' }] },
      ],
    },
  },
  {
    id: 'rechnung',
    name: 'Rechnung',
    description: 'Rechnungsvorlage mit Tabelle.',
    category: 'geschaeftlich',
    content: {
      type: 'doc',
      content: [
        { type: 'paragraph', attrs: { textAlign: 'right' }, content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'RECHNUNG' }] },
        { type: 'paragraph', attrs: { textAlign: 'right' }, content: [{ type: 'text', text: 'Rechnungsnr.: 2024-001' }] },
        { type: 'paragraph', attrs: { textAlign: 'right' }, content: [{ type: 'text', text: 'Datum: ' + new Date().toLocaleDateString('de-CH') }] },
        { type: 'paragraph' },
        { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Absender:' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Ihre Firma GmbH | Musterstrasse 1 | 8000 Zuerich' }] },
        { type: 'paragraph' },
        { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Empfaenger:' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Kunde AG | Kundenstrasse 2 | 3000 Bern' }] },
        { type: 'paragraph' },
        { type: 'horizontalRule' },
        { type: 'paragraph', content: [{ type: 'text', text: 'Bitte begleichen Sie den Rechnungsbetrag innert 30 Tagen.' }] },
        { type: 'paragraph' },
        { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'IBAN: CH00 0000 0000 0000 0000 0' }] },
      ],
    },
  },
]
