import type { ThemeDefinition } from './types/styles'

export const DEFAULT_THEMES: ThemeDefinition[] = [
  {
    name: 'office',
    displayName: 'Office',
    headingFont: 'Calibri',
    bodyFont: 'Times New Roman',
    primaryColor: '#1a5276',
    accentColor: '#0078d4',
    headingColor: '#1a5276',
    bodyColor: '#000000',
  },
  {
    name: 'modern',
    displayName: 'Modern',
    headingFont: 'Arial',
    bodyFont: 'Arial',
    primaryColor: '#2c3e50',
    accentColor: '#3498db',
    headingColor: '#2c3e50',
    bodyColor: '#333333',
  },
  {
    name: 'elegant',
    displayName: 'Elegant',
    headingFont: 'Georgia',
    bodyFont: 'Georgia',
    primaryColor: '#4a4a4a',
    accentColor: '#8b5e3c',
    headingColor: '#4a4a4a',
    bodyColor: '#333333',
  },
  {
    name: 'academic',
    displayName: 'Akademisch',
    headingFont: 'Times New Roman',
    bodyFont: 'Times New Roman',
    primaryColor: '#000000',
    accentColor: '#1a5276',
    headingColor: '#000000',
    bodyColor: '#000000',
  },
  {
    name: 'creative',
    displayName: 'Kreativ',
    headingFont: 'Trebuchet MS',
    bodyFont: 'Verdana',
    primaryColor: '#e74c3c',
    accentColor: '#e67e22',
    headingColor: '#e74c3c',
    bodyColor: '#2c3e50',
  },
  {
    name: 'minimal',
    displayName: 'Minimalistisch',
    headingFont: 'Helvetica',
    bodyFont: 'Helvetica',
    primaryColor: '#555555',
    accentColor: '#888888',
    headingColor: '#333333',
    bodyColor: '#444444',
  },
]
