import type { StyleDefinition } from './types/styles'

export const DEFAULT_STYLES: StyleDefinition[] = [
  {
    name: 'normal',
    displayName: 'Normal',
    fontFamily: 'Times New Roman',
    fontSize: '12pt',
    fontWeight: 400,
    fontStyle: 'normal',
    color: '#000000',
    textAlign: 'left',
    lineHeight: '1.5',
    spaceBefore: '0pt',
    spaceAfter: '8pt',
    indent: 0,
  },
  {
    name: 'heading1',
    displayName: 'Ueberschrift 1',
    basedOn: 'normal',
    fontFamily: 'Calibri',
    fontSize: '24pt',
    fontWeight: 700,
    color: '#1a5276',
    lineHeight: '1.2',
    spaceBefore: '12pt',
    spaceAfter: '6pt',
    isHeading: true,
    headingLevel: 1,
  },
  {
    name: 'heading2',
    displayName: 'Ueberschrift 2',
    basedOn: 'normal',
    fontFamily: 'Calibri',
    fontSize: '18pt',
    fontWeight: 700,
    color: '#1a5276',
    lineHeight: '1.3',
    spaceBefore: '10pt',
    spaceAfter: '4pt',
    isHeading: true,
    headingLevel: 2,
  },
  {
    name: 'heading3',
    displayName: 'Ueberschrift 3',
    basedOn: 'normal',
    fontFamily: 'Calibri',
    fontSize: '14pt',
    fontWeight: 600,
    color: '#2c3e50',
    lineHeight: '1.3',
    spaceBefore: '8pt',
    spaceAfter: '4pt',
    isHeading: true,
    headingLevel: 3,
  },
  {
    name: 'heading4',
    displayName: 'Ueberschrift 4',
    basedOn: 'normal',
    fontFamily: 'Calibri',
    fontSize: '12pt',
    fontWeight: 600,
    color: '#2c3e50',
    lineHeight: '1.4',
    spaceBefore: '6pt',
    spaceAfter: '3pt',
    isHeading: true,
    headingLevel: 4,
  },
  {
    name: 'heading5',
    displayName: 'Ueberschrift 5',
    basedOn: 'normal',
    fontFamily: 'Calibri',
    fontSize: '11pt',
    fontWeight: 600,
    color: '#34495e',
    isHeading: true,
    headingLevel: 5,
  },
  {
    name: 'heading6',
    displayName: 'Ueberschrift 6',
    basedOn: 'normal',
    fontFamily: 'Calibri',
    fontSize: '10pt',
    fontWeight: 600,
    color: '#34495e',
    fontStyle: 'italic',
    isHeading: true,
    headingLevel: 6,
  },
  {
    name: 'title',
    displayName: 'Titel',
    fontFamily: 'Calibri',
    fontSize: '28pt',
    fontWeight: 300,
    color: '#1a5276',
    textAlign: 'left',
    lineHeight: '1.15',
    spaceBefore: '0pt',
    spaceAfter: '12pt',
  },
  {
    name: 'subtitle',
    displayName: 'Untertitel',
    fontFamily: 'Calibri',
    fontSize: '16pt',
    fontWeight: 400,
    color: '#7f8c8d',
    fontStyle: 'italic',
    lineHeight: '1.3',
    spaceBefore: '0pt',
    spaceAfter: '12pt',
  },
  {
    name: 'quote',
    displayName: 'Zitat',
    fontFamily: 'Georgia',
    fontSize: '12pt',
    fontWeight: 400,
    fontStyle: 'italic',
    color: '#4b5563',
    textAlign: 'left',
    lineHeight: '1.6',
    spaceBefore: '6pt',
    spaceAfter: '6pt',
    indent: 1,
  },
  {
    name: 'listParagraph',
    displayName: 'Listenabsatz',
    basedOn: 'normal',
    indent: 1,
  },
  {
    name: 'noSpacing',
    displayName: 'Kein Abstand',
    fontFamily: 'Times New Roman',
    fontSize: '12pt',
    fontWeight: 400,
    lineHeight: '1.0',
    spaceBefore: '0pt',
    spaceAfter: '0pt',
  },
  {
    name: 'compact',
    displayName: 'Kompakt',
    fontFamily: 'Arial',
    fontSize: '10pt',
    fontWeight: 400,
    lineHeight: '1.15',
    spaceBefore: '0pt',
    spaceAfter: '4pt',
  },
]
